# Generated by Django 2.2.5 on 2020-01-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0006_auto_20191205_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='prestation',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='quantite',
        ),
        migrations.AddField(
            model_name='facture',
            name='prestToFact',
            field=models.ManyToManyField(to='facture.PrestToFact'),
        ),
    ]
