# Generated by Django 2.2.5 on 2020-01-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0007_auto_20200120_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='prestToFact',
        ),
        migrations.RemoveField(
            model_name='prestataire',
            name='TVA',
        ),
        migrations.AddField(
            model_name='prestataire',
            name='tva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
    ]
