# Generated by Django 2.2.5 on 2020-01-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0008_auto_20200120_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='quantite',
            field=models.IntegerField(default=0),
        ),
    ]
