# Generated by Django 2.2.5 on 2020-01-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0009_facture_quantite'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='prestToFact',
            field=models.ManyToManyField(to='facture.PrestToFact'),
        ),
        migrations.AddField(
            model_name='facture',
            name='prestation',
            field=models.ManyToManyField(to='facture.Prestation'),
        ),
    ]
