# Generated by Django 2.2.5 on 2020-01-20 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0010_auto_20200120_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='prestation',
        ),
        migrations.AddField(
            model_name='facture',
            name='prestation',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='facture.Prestation'),
            preserve_default=False,
        ),
    ]
