# Generated by Django 2.2.5 on 2020-01-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0012_auto_20200120_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='prestToFact',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='prestation',
        ),
        migrations.AddField(
            model_name='facture',
            name='prestation',
            field=models.ManyToManyField(to='facture.Prestation'),
        ),
    ]
